language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

install:
  # installing mongodb
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/10gen.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-10gen

  # installing redis-server
  - sudo apt-get install -y redis-server

  # install python requirements
  - pip install -e .[tests]

script:
    # finally run tests
    - make ci-test
